### PR TITLE
Update qi_functions.php

### PR DESCRIPTION
**Pull request by 3D-I**
postgres issue 75 

untested

### CODE REVIEW

**Comment by VSEphpbb** [comment]
This change does not work. It has to be pgsql or else it fails a few lines down:
https://github.com/phpbb/quickinstall/pull/76/files#diff-ecede71a8c4fd78b82688676f94052a9R40

**Comment by 3D-I** [comment]
Correct.
http://php.net/manual/en/function.get-loaded-extensions.php

**Comment by DavidIQ** [comment]
I think the change might need to be something closer to what is here:
https://github.com/phpbb/phpbb/blob/3.2.x/phpBB/phpbb/install/helper/database.php#L84

In fact it might be better to just implement usage of this helper class in qi.

**Comment by VSEphpbb** [comment]
Except that particular class does not exits in 3.1

**Comment by DavidIQ** [comment]
Copy/paste it is then :-P

**Comment by 3D-I** [comment]
Indeed, what about 3.0? Should the whole QI's support be dropped?

**Comment by DavidIQ** [comment]
If it's not in the way and is not preventing us from doing certain things to resolve this issue then we can just leave it alone. It's outside of the scope for this bug anyways.

**Comment by VSEphpbb** [comment]
Replaced by https://github.com/phpbb/quickinstall/pull/77

**Pull request closed without merging**
